### ISSUE TITLE
Does not transfer workouts to Pebble

### ISSUE THREAD

**Issue by tmlye** [jscottnz/jim-config#1]
Hi,
I have a Pebble Time and configured some workouts on my phone. When I press the Send-To-Phone Button, nothing happens.
What can I do to debug this?

**Comment by jscottnz** [comment]
from the pebble app, make sure that you “tick” the workout so that there is a green tick next to it. then press the watch button.

let me know if that doesn’t work

**Comment by tmlye** [comment]
Thank you, that worked! I kept trying on the "Routines" screen and nothing happend. I thought you transfer everything and then select the workout on the watch.
